version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: db_mysql_tiramisu
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql

  # créer un container phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: db_phpmyadmin_tiramisu
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT} #3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      # sert a R marche pas tout est pris dans le schema.prisma dans tous les cas!
      - DATABASE_URL=mysql://root:Taster_root+123@BOCAL-2023%@db_mysql_tiramisu:3306/tiramisu_bases
    depends_on:
      - db
      - phpmyadmin
